# ---------------------------------------------------------------------------
# gisbuild_layer.py
# Created on: 2013-08-14 11:35:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# Regenerate featureclass WG_BR_AXEBLADE from source table with xy values
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os, datetime
arcpy.env.overwriteOutput = True

# Local variables:
WCSS_SOURCE = "D:/SpatialAdapters/ArcCatalog/OLE DB ConnectionWCSS.odc/WCSS.BR_AXEBLADE_MV"
WCSS_Layer = "WCSS_Layer"
SIIGIS_WG_LAYER = "d:/SpatialAdapters/ArcCatalog/Connection to US1190SQLI01 as gismaster.sde/WellsGIS.GIS_MASTER.WG_BR_AXEBLADE"
now = datetime.datetime.now()

print "GisBuild of BR_AXEBLADE"
print "Started: " + str(now)

try:

    if arcpy.Exists(WCSS_SOURCE):
	# Process: Make XY Event Layer
	print "Source Table Exists"
	arcpy.MakeXYEventLayer_management(WCSS_SOURCE, "longitude", "latitude", WCSS_Layer, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision", "")
	print "Make XY Layer Succeeded"
	if arcpy.Exists(WCSS_Layer):
		print "Proceed to Copy Features"
		# Process: Copy Features
		if arcpy.Exists(SIIGIS_WG_LAYER):
			print "Delete FeatureClass"
			arcpy.Delete_management(SIIGIS_WG_LAYER)
			print "Delete FeatureClass Succeeded"
		print "Begin Copy Features Management"
		arcpy.CopyFeatures_management(WCSS_Layer, SIIGIS_WG_LAYER, "", "0", "0", "0")
		print "All Features Copied\n"
    now = datetime.datetime.now()
    print "Ended: " + str(now) + "\n"

except: 
   arcpy.AddError("Python Messages: " + arcpy.GetMessages()) 

